---
- name: Strength
  campaign: call-of-cthulhu-1920
- name: Dexterity
  campaign: call-of-cthulhu-1920
- name: Intelligence
  campaign: call-of-cthulhu-1920
- name: Constitution
  campaign: call-of-cthulhu-1920
- name: Appearance
  campaign: call-of-cthulhu-1920
- name: Power
  campaign: call-of-cthulhu-1920
- name: Size
  campaign: call-of-cthulhu-1920
- name: Education
  campaign: call-of-cthulhu-1920
