u = User.first
camp = Campaign.create!(name: 'Masks of Nyarlathotep')
u.owned_campaigns << camp
u.save

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Neil", "last_name"=>"Hayward", "occupation"=>"Parapsychologist", "degrees"=>"Bachelors", "birthplace"=>"Fontana, California", "gender"=>"m", "age"=>41, "weapon_ids"=>nil, "residence"=>nil, "personal_description"=>nil, "family_and_friends"=>nil, "episodes_of_insanity"=>nil, "wounds_and_injuries"=>nil, "marks_and_scars"=>nil, "history"=>nil, "income"=>nil, "cash"=>nil, "savings"=>nil, "property"=>nil, "real_estate"=>nil})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>11, "dexterity"=>12, "intelligence"=>15, "constitution"=>12, "appearance"=>10, "power"=>13, "size"=>5, "education"=>15})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"parapsychologist", "accounting"=>nil, "anthropology"=>30, "archaeology"=>50, "astronomy"=>nil, "bargain"=>nil, "biology"=>nil, "chemistry"=>nil, "climb"=>nil, "conceal"=>nil, "credit_rating"=>nil, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>nil, "drive_auto"=>nil, "electrical_repair"=>nil, "fast_talk"=>nil, "first_aid"=>nil, "geology"=>nil, "hide"=>nil, "history"=>25, "jump"=>nil, "law"=>nil, "library_use"=>45, "listen"=>45, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>nil, "natural_history"=>nil, "navigate"=>nil, "occult"=>90, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>nil, "pharmacy"=>nil, "photography"=>10, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>65, "ride"=>nil, "sneak"=>nil, "spot_hidden"=>60, "swim"=>nil, "throw"=>nil, "track"=>30, "handgun"=>nil, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>nil, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>"[\"spot_hidden\"]"})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Alexander", "last_name"=>"Shackleton", "occupation"=>"Dean Antiq/Anthro dept.", "degrees"=>"PhD  Antiquities/Anthropology", "birthplace"=>"Boston, MA", "gender"=>"m", "age"=>48, "weapon_ids"=>"39", "residence"=>"", "personal_description"=>"- always clad in tweed suit, somewhat frayed but tidy.\r\n", "family_and_friends"=>"-never married, no kids ", "episodes_of_insanity"=>"one in the JUJU house basement", "wounds_and_injuries"=>"", "marks_and_scars"=>"", "history"=>"", "income"=>"30000", "cash"=>"a good amount", "savings"=>"never spent much, as he was never married ", "property"=>"", "real_estate"=>"Row house located just off campus at Miskatonic University"})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>12, "dexterity"=>9, "intelligence"=>12, "constitution"=>12, "appearance"=>8, "power"=>12, "size"=>10, "education"=>13})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"professor", "accounting"=>nil, "anthropology"=>85, "archaeology"=>75, "astronomy"=>nil, "bargain"=>67, "biology"=>nil, "chemistry"=>nil, "climb"=>nil, "conceal"=>nil, "credit_rating"=>55, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>nil, "drive_auto"=>nil, "electrical_repair"=>nil, "fast_talk"=>nil, "first_aid"=>nil, "geology"=>nil, "hide"=>nil, "history"=>nil, "jump"=>nil, "law"=>nil, "library_use"=>55, "listen"=>2, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>nil, "natural_history"=>nil, "navigate"=>nil, "occult"=>nil, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>57, "pharmacy"=>nil, "photography"=>nil, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>nil, "ride"=>nil, "sneak"=>nil, "spot_hidden"=>nil, "swim"=>nil, "throw"=>nil, "track"=>nil, "handgun"=>nil, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>7, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>"[\"anthropology\",\"archaeology\"]"})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Zenobia", "last_name"=>"Watkins", "occupation"=>"Explorer/Hunter", "degrees"=>"Bachelors", "birthplace"=>"Warwick, Rhode Island", "gender"=>"f", "age"=>31, "weapon_ids"=>"8,50", "residence"=>nil, "personal_description"=>nil, "family_and_friends"=>nil, "episodes_of_insanity"=>nil, "wounds_and_injuries"=>nil, "marks_and_scars"=>nil, "history"=>nil, "income"=>nil, "cash"=>nil, "savings"=>nil, "property"=>nil, "real_estate"=>nil})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>16, "dexterity"=>15, "intelligence"=>15, "constitution"=>13, "appearance"=>14, "power"=>15, "size"=>12, "education"=>8})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"other", "accounting"=>nil, "anthropology"=>nil, "archaeology"=>nil, "astronomy"=>nil, "bargain"=>nil, "biology"=>nil, "chemistry"=>nil, "climb"=>10, "conceal"=>nil, "credit_rating"=>nil, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>nil, "drive_auto"=>20, "electrical_repair"=>nil, "fast_talk"=>nil, "first_aid"=>20, "geology"=>nil, "hide"=>nil, "history"=>nil, "jump"=>nil, "law"=>nil, "library_use"=>nil, "listen"=>25, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>nil, "natural_history"=>nil, "navigate"=>30, "occult"=>nil, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>nil, "pharmacy"=>nil, "photography"=>nil, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>nil, "ride"=>nil, "sneak"=>20, "spot_hidden"=>40, "swim"=>10, "throw"=>nil, "track"=>40, "handgun"=>nil, "machine_gun"=>nil, "rifle"=>55, "shotgun"=>nil, "SMG"=>nil, "fist"=>nil, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>40, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>"[\"drive_auto\",\"melee\",\"rifle\",\"track\",\"spot_hidden\",\"swim\",\"sneak\",\"first_aid\"]"})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Virginia \"Vinnie\" ", "last_name"=>"Hunt", "occupation"=>"Journalist", "degrees"=>"Composition", "birthplace"=>"Brooklyn, NY", "gender"=>"f", "age"=>25, "weapon_ids"=>nil, "residence"=>nil, "personal_description"=>nil, "family_and_friends"=>nil, "episodes_of_insanity"=>nil, "wounds_and_injuries"=>nil, "marks_and_scars"=>nil, "history"=>nil, "income"=>nil, "cash"=>nil, "savings"=>nil, "property"=>nil, "real_estate"=>nil})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>13, "dexterity"=>17, "intelligence"=>17, "constitution"=>13, "appearance"=>17, "power"=>14, "size"=>13, "education"=>16})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"journalist", "accounting"=>nil, "anthropology"=>nil, "archaeology"=>nil, "astronomy"=>nil, "bargain"=>40, "biology"=>nil, "chemistry"=>nil, "climb"=>nil, "conceal"=>25, "credit_rating"=>nil, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>nil, "drive_auto"=>nil, "electrical_repair"=>nil, "fast_talk"=>60, "first_aid"=>nil, "geology"=>nil, "hide"=>25, "history"=>40, "jump"=>nil, "law"=>nil, "library_use"=>50, "listen"=>50, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>nil, "natural_history"=>nil, "navigate"=>nil, "occult"=>15, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>55, "pharmacy"=>nil, "photography"=>5, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>60, "ride"=>nil, "sneak"=>25, "spot_hidden"=>40, "swim"=>nil, "throw"=>nil, "track"=>nil, "handgun"=>nil, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>nil, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>"[\"listen\"]"})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Dominick", "last_name"=>"Grainger", "occupation"=>"Engineer", "degrees"=>"BS Engineering", "birthplace"=>"Fort Worth, Texas", "gender"=>"m", "age"=>51, "weapon_ids"=>nil, "residence"=>"Little Rock, Arkansas", "personal_description"=>"Great engineer, family man, no church, loves his kids, big into science,", "family_and_friends"=>"Wife 3 kids.  Dead father, mother stays with his sister in Fort Worth.", "episodes_of_insanity"=>"123456789012345678901234567890123456789012", "wounds_and_injuries"=>"N/A", "marks_and_scars"=>"Appendectemy scar", "history"=>"-I was born on the wrong side of the tracks with an absent father and a sickly mother.  \r\n-I took care of my sister and we managed to scrape by.  I did well in school, and made it a priority to go to college.  \r\n-My sister married well, so we've both moved up to the middle class in adulthood. I was born on the wrong side of the tracks with an absent father and a sickly mother.  \r\n-I took care of my sister and we managed to scrape by.  I did well in school, and made it a priority to go to college.", "income"=>"20000", "cash"=>"$5,000", "savings"=>"$15,000", "property"=>"Car", "real_estate"=>"House"})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>16, "dexterity"=>10, "intelligence"=>11, "constitution"=>13, "appearance"=>9, "power"=>5, "size"=>12, "education"=>12})
c.skill_set = Coc::SkillSet.create!({"campaign" => camp, "skill_occupation"=>"athlete", "accounting"=>nil, "anthropology"=>nil, "archaeology"=>nil, "astronomy"=>nil, "bargain"=>nil, "biology"=>nil, "chemistry"=>nil, "climb"=>nil, "conceal"=>nil, "credit_rating"=>nil, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>nil, "drive_auto"=>nil, "electrical_repair"=>nil, "fast_talk"=>nil, "first_aid"=>nil, "geology"=>nil, "hide"=>nil, "history"=>nil, "jump"=>nil, "law"=>nil, "library_use"=>nil, "listen"=>nil, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>nil, "natural_history"=>nil, "navigate"=>nil, "occult"=>nil, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>nil, "pharmacy"=>nil, "photography"=>nil, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>nil, "ride"=>nil, "sneak"=>nil, "spot_hidden"=>nil, "swim"=>nil, "throw"=>nil, "track"=>nil, "handgun"=>nil, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>nil, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>"[\"biology\"]"})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Roscoe", "last_name"=>"Higgins", "occupation"=>"Aviator", "degrees"=>"Bachelors", "birthplace"=>"Gresham, Oregon", "gender"=>"m", "age"=>44, "weapon_ids"=>"8,36", "residence"=>"Garland, Texas", "personal_description"=>"", "family_and_friends"=>"", "episodes_of_insanity"=>"", "wounds_and_injuries"=>"", "marks_and_scars"=>"", "history"=>"", "income"=>"5000.0", "cash"=>"", "savings"=>"", "property"=>"", "real_estate"=>""})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>10, "dexterity"=>15, "intelligence"=>13, "constitution"=>9, "appearance"=>12, "power"=>10, "size"=>9, "education"=>12})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"", "accounting"=>nil, "anthropology"=>nil, "archaeology"=>nil, "astronomy"=>nil, "bargain"=>nil, "biology"=>nil, "chemistry"=>nil, "climb"=>nil, "conceal"=>nil, "credit_rating"=>nil, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>21, "drive_auto"=>nil, "electrical_repair"=>60, "fast_talk"=>nil, "first_aid"=>50, "geology"=>nil, "hide"=>nil, "history"=>nil, "jump"=>nil, "law"=>nil, "library_use"=>nil, "listen"=>nil, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>nil, "natural_history"=>nil, "navigate"=>49, "occult"=>nil, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>nil, "pharmacy"=>nil, "photography"=>nil, "physics"=>30, "psychoanalysis"=>nil, "psychology"=>nil, "ride"=>nil, "sneak"=>nil, "spot_hidden"=>70, "swim"=>nil, "throw"=>nil, "track"=>nil, "handgun"=>61, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>20, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{\"Bomber\":\"80\"}", "other"=>nil, "occupation_skills"=>""})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Lem", "last_name"=>"Baxter", "occupation"=>"Locksmith", "degrees"=>"He won't say", "birthplace"=>"Round Rock, Texas", "gender"=>"m", "age"=>30, "weapon_ids"=>"39", "residence"=>"New York City", "personal_description"=>"Conspiracy Theorist, unafraid to break n enter (fun pass-time), slightly racist", "family_and_friends"=>"", "episodes_of_insanity"=>"", "wounds_and_injuries"=>"", "marks_and_scars"=>"", "history"=>"", "income"=>"1000.0", "cash"=>"", "savings"=>"", "property"=>"", "real_estate"=>""})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>11, "dexterity"=>12, "intelligence"=>10, "constitution"=>16, "appearance"=>11, "power"=>12, "size"=>10, "education"=>17})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"", "accounting"=>nil, "anthropology"=>nil, "archaeology"=>nil, "astronomy"=>nil, "bargain"=>nil, "biology"=>nil, "chemistry"=>nil, "climb"=>nil, "conceal"=>19, "credit_rating"=>nil, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>23, "drive_auto"=>nil, "electrical_repair"=>nil, "fast_talk"=>59, "first_aid"=>nil, "geology"=>nil, "hide"=>nil, "history"=>nil, "jump"=>nil, "law"=>20, "library_use"=>19, "listen"=>47, "locksmith"=>80, "martial_arts"=>nil, "mechanical_repair"=>55, "medicine"=>nil, "natural_history"=>nil, "navigate"=>nil, "occult"=>nil, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>nil, "pharmacy"=>nil, "photography"=>20, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>nil, "ride"=>nil, "sneak"=>40, "spot_hidden"=>45, "swim"=>nil, "throw"=>nil, "track"=>nil, "handgun"=>36, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>15, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>""})

c = Coc::Character.create!({"campaign" => camp, "first_name"=>"Magnolia", "last_name"=>"Appleton", "occupation"=>"Nurse", "degrees"=>"Natural Science", "birthplace"=>"Mount Vernon, New York", "gender"=>"f", "age"=>27, "weapon_ids"=>nil, "residence"=>"", "personal_description"=>"Moved to the city to go to university, got a job as a nurse after graduation and could afford to stay in the city. Liked the night life. ", "family_and_friends"=>"Has some nurse friends, was friends with neighbor across the street, has a cat. Parents alive in upstate New York. ", "episodes_of_insanity"=>"None yet but traumatized by recent kidnapping. Nervous around fire, chance of freaking out a bit if bound.", "wounds_and_injuries"=>"", "marks_and_scars"=>"", "history"=>"Loves animals and great sense of empathy. Plays piano rather badly. Loves jazz. Good at math, languages. ", "income"=>"10000", "cash"=>"$30.00", "savings"=>"$1000", "property"=>"One cat. Rents. Nothing to speak of.  ", "real_estate"=>""})
c.characteristic_set = Coc::CharacteristicSet.create!({"strength"=>11, "dexterity"=>13, "intelligence"=>17, "constitution"=>13, "appearance"=>14, "power"=>12, "size"=>8, "education"=>15})
c.skill_set = Coc::SkillSet.create!({"skill_occupation"=>"", "accounting"=>nil, "anthropology"=>nil, "archaeology"=>nil, "astronomy"=>nil, "bargain"=>nil, "biology"=>64, "chemistry"=>29, "climb"=>nil, "conceal"=>nil, "credit_rating"=>10, "cthulhu_mythos"=>nil, "disguise"=>nil, "dodge"=>8, "drive_auto"=>9, "electrical_repair"=>nil, "fast_talk"=>27, "first_aid"=>51, "geology"=>nil, "hide"=>nil, "history"=>nil, "jump"=>nil, "law"=>nil, "library_use"=>19, "listen"=>50, "locksmith"=>nil, "martial_arts"=>nil, "mechanical_repair"=>nil, "medicine"=>69, "natural_history"=>nil, "navigate"=>nil, "occult"=>10, "operate_heavy_machine"=>nil, "own_language"=>nil, "persuade"=>52, "pharmacy"=>54, "photography"=>nil, "physics"=>nil, "psychoanalysis"=>nil, "psychology"=>58, "ride"=>nil, "sneak"=>8, "spot_hidden"=>28, "swim"=>nil, "throw"=>nil, "track"=>nil, "handgun"=>10, "machine_gun"=>nil, "rifle"=>nil, "shotgun"=>nil, "SMG"=>nil, "fist"=>nil, "grapple"=>nil, "head"=>nil, "kick"=>nil, "melee"=>nil, "art"=>"{}", "craft"=>"{}", "other_language"=>"{\"Latin\":\"18\"}", "pilot"=>"{}", "other"=>nil, "occupation_skills"=>""})

