class AddDgSkillSet < ActiveRecord::Migration
  def change
    create_table :dg_skill_sets do |t|
      t.integer :accounting
      t.integer :alertness
      t.integer :anthropology
      t.integer :archeology
      t.integer :art_1
      t.integer :art_2
      t.integer :art_3
      t.string :art_1_text
      t.string :art_2_text
      t.string :art_3_text
      t.integer :artillery
      t.integer :athletics
      t.integer :bureaucracy
      t.integer :computer_science
      t.integer :craft_1
      t.integer :craft_2
      t.integer :craft_3
      t.string :craft_1_text
      t.string :craft_2_text
      t.string :craft_3_text
      t.integer :criminology
      t.integer :demolitions
      t.integer :disguise
      t.integer :dodge
      t.integer :drive
      t.integer :firearms
      t.integer :first_aid
      t.integer :forensics
      t.integer :humint
      t.integer :heavy_machinery
      t.integer :heavy_weapons
      t.integer :history
      t.integer :law
      t.integer :medicine
      t.integer :melee_weapons
      t.integer :military_science_1
      t.integer :military_science_2
      t.integer :military_science_3
      t.string :military_science_1_text
      t.string :military_science_2_text
      t.string :military_science_3_text
      t.integer :navigate
      t.integer :occult
      t.integer :persuade
      t.integer :pharmacy
      t.integer :pilot_1
      t.integer :pilot_2
      t.integer :pilot_3
      t.string :pilot_1_text
      t.string :pilot_2_text
      t.string :pilot_3_text
      t.integer :psychotherapy
      t.integer :ride
      t.integer :sigint
      t.integer :science_1
      t.integer :science_2
      t.integer :science_3
      t.string :science_1_text
      t.string :science_2_text
      t.string :science_3_text
      t.integer :search
      t.integer :stealth
      t.integer :surgery
      t.integer :survival
      t.integer :swim
      t.integer :unarmed_combat
      t.integer :unnatural
      t.integer :foreign_language_1
      t.integer :foreign_language_2
      t.integer :foreign_language_3
      t.string :foreign_language_1_text
      t.string :foreign_language_2_text
      t.string :foreign_language_3_text
      t.references :character
      t.string :occupation
      t.integer :bonds
      t.string :bonus_skill_package
      t.timestamps
    end
  end
end
